version: '3.1'

services:
  mysql:
    container_name: YodeckScreenDB
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Hallo.123
      MYSQL_DATABASE: dwlscreen
      MYSQL_USER: dwluser
      MYSQL_PASSWORD: Hallo.123
    ports:
      - "3306:3306"
    volumes:
      - DWLyodeckscreen:/var/lib/mysql
      - ./DBimport:/docker-entrypoint-initdb.d
      
  
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: Hallo.123
    ports:
      - "7098:80"
      

  nginx_Static:
    container_name: StaticNginxSite
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./StaticHtml/index.html:/usr/share/nginx/html/index.html
      - ./StaticHtml/style.css:/usr/share/nginx/html/style.css
      - ./StaticHtml/frontend.js:/usr/share/nginx/html/frontend.js
      - ./Statichtml/ressources:/usr/share/nginx/html/ressources


  java_app:
    container_name: javaBackend
    image: openjdk:latest
    restart: always
    command: java -jar /app/Backend.jar
    volumes:
      - ./javaBackend/Backend.jar:/app/Backend.jar
    ports:
      - "8887:8887" 

volumes:
  DWLyodeckscreen:
