version: '3'

services:
  db:
    container_name: mysql
    build:
      context: ./db
      dockerfile: DOCKERFILE
    restart: always
    env_file:
      - logins.env
    networks:
      yodeck_net:
        ipv4_address: 172.168.0.2
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  java_backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: DOCKERFILE
    restart: always
    depends_on:
      - db
    networks:
      yodeck_net:
        ipv4_address: 172.168.0.3
    ports:
      - "8887:8887"

  nginx:
    container_name: nginx
    build:
      context: ./site
      dockerfile: DOCKERFILE
    restart: always
    networks:
      yodeck_net:
        ipv4_address: 172.168.0.4
    ports:
      - "8000:80"


  phpmyadmin:
    container_name: phpmyadmin1
    image: phpmyadmin/phpmyadmin:latest
    networks:
      yodeck_net:
        ipv4_address: 172.168.0.5
    ports:
      - "8001:80"
    links:
      - db:db
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306


  import:
    container_name: csvimport
    build:
      context: ./CSVimport
      dockerfile: DOCKERFILE
    restart: always
    networks:
      yodeck_net:
        ipv4_address: 172.168.0.6
    ports:
      - "8002:80"

networks:
  yodeck_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.168.0.0/24
          gateway: 172.168.0.1

volumes:
  db_data:

